#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: "3.7"
networks:
  dspacenet:
services:
  dspace:
    container_name: dspace
    depends_on:
      - dspacedb
    image: dspace/dspace:dspace-6_x-jdk8
    networks:
      dspacenet:
    ports:
      - published: 8080
        target: 8080
    stdin_open: true
    tty: true
    volumes:
      - assetstore:/dspace/assetstore
      - solr_authority:/dspace/solr/authority/data
      - solr_oai:/dspace/solr/oai/data
      - solr_search:/dspace/solr/search/data
      - solr_statistics:/dspace/solr/statistics/data
  dspacedb:
    container_name: dspacedb
    environment:
      PGDATA: /pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    image: dspace/dspace-postgres-pgcrypto
    networks:
      dspacenet:
    stdin_open: true
    tty: true
    volumes:
      - pgdata:/pgdata
volumes:
  assetstore:
  pgdata:
  solr_authority:
  solr_oai:
  solr_search:
  solr_statistics:
